import { Document, Types } from 'mongoose';
export type ProjectType = Document & {
  projectId: string;
  name: string;
  budget: number;
  advance: number;
  due: number;
  client: string;
  clientPhone: string;
  clientEmail: string;
  clientAddress: string;
  clientDetails: string;
  startDate: string;
  endDate: string;
  demoLink: string;
  typeOfWeb: string;
  description: string;
  status: boolean;
  verifiedClientList: Types.ObjectId[];
  projectManager: Types.ObjectId;
};
